YOLOTOL/SOURCE_CODE/Controllers/CatalogoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YOLOTOL.Data;
using YOLOTOL.Helpers;
using YOLOTOL.Models;

namespace YOLOTOL.Controllers
{
    public class CatalogoController : Controller
    {
        private readonly YolotolContext _context;
        public CatalogoController(YolotolContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");//Obtener la lista
            if (cart != null)
            {
                ViewBag.count = cart.Count;//Contando el número de elementos en el carrito
                ViewBag.cart = cart;//Elementos del carrito
                ViewBag.total = cart.Sum(item => item.Producto.Precio * item.Quantity);//calCULO total = x cada elemento del cart presio*cantidad
                ViewBag.cantidad = cart.Sum(item => item.Quantity);//Calculo cantidad
            }
            return View(await _context.Producto.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var producto = await _context.Producto.FirstOrDefaultAsync(m => m.IdProducto == id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        public async Task<IActionResult> ShoppingCart()
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");//Obtener la lista
            if (cart != null)
            {
                ViewBag.count = cart.Count;//Contando el número de elementos en el carrito
                ViewBag.cart = cart;//Elementos del carrito
                ViewBag.total = cart.Sum(item => item.Producto.Precio * item.Quantity);//calCULO total = x cada elemento del cart presio*cantidad
                ViewBag.cantidad = cart.Sum(item => item.Quantity);//Calculo cantidad
            }
            return View(await _context.Producto.ToListAsync());
        }

        public async Task<IActionResult> AddToCart(int? id)
        {
            Productos productos = new Productos();
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                List<CartItem> cart = new List<CartItem>();//Crear variable(carrito)
                var producto = await _context.Producto.FirstOrDefaultAsync(m => m.IdProducto == id);//Busca el producto y lo guarda
                cart.Add(new CartItem { Producto = producto, Quantity = 1 });//Agrega el elemento al carrito, es decir el producto o la cantidad
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);//El elemento del carrito lo guarda en la sesión
            }
            else
            {
                List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    var producto = await _context.Producto.FirstOrDefaultAsync(m => m.IdProducto == id);//Busca el producto y lo guarda
                    cart.Add(new CartItem { Producto = producto, Quantity = 1 });//Agrega el elemento al carrito, es decir el producto o la cantidad
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);//El elemento del carrito lo guarda en la sesión

            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Update(int? id, int quantity)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");//Obtener la lista
            int index = isExist(id);
            if (index != -1)
            {
                cart[index].Quantity = quantity;
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("ShoppingCart");

        }

        public async Task<IActionResult> Remove(int? id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");//Obtener la lista
            int index = isExist(id);
            if (index != -1 && cart.Count > 1)
            {
                cart.RemoveAt(index);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else if (index != -1 && cart.Count == 1)
            {
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", null);
            }
            return RedirectToAction("ShoppingCart");

        }

        private int isExist(int? id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Producto.IdProducto.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

YOLOTOL/SOURCE_CODE/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace YOLOTOL.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Datos()
        {
            return View();
        }
        public IActionResult Perfil()
        {
            return View();
        }
        public IActionResult Logros()
        {
            return View();
        }
    }
}

YOLOTOL/SOURCE_CODE/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YOLOTOL.Data;
using YOLOTOL.Helpers;
using YOLOTOL.Models;

namespace YOLOTOL.Controllers
{
    public class ProductosController : Controller
    {
        private readonly YolotolContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;


        public ProductosController(YolotolContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;

        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
            String tipoUsuario = SessionHelper.GetObjectFromJson<String>(HttpContext.Session, "tipoUsuario");
            if (User.Identity.IsAuthenticated)
            {
                if (tipoUsuario == "Administrador")
                {
                    return View(await _context.Producto.ToListAsync());
                }
            }
            return RedirectToAction("Error", "Usuarios");
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productos = await _context.Producto
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (productos == null)
            {
                return NotFound();
            }

            return View(productos);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nombre");
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProducto,Nombre,Archivo,Precio,Stock,Descripcion,IdCategoria")] Productos productos)
        {
            if (ModelState.IsValid)
            {
                if (productos.Archivo != null)
                {
                    // Guardar la imagen en wwwroot/imagenes
                    string rutaCarpeta = webHostEnvironment.WebRootPath;
                    string nombreArchivo = Path.GetFileNameWithoutExtension(productos.Archivo.FileName);
                    string extension = Path.GetExtension(productos.Archivo.FileName);
                    //Asignar al atributo
                    productos.Imagen = nombreArchivo = 
                        nombreArchivo + DateTime.Now.ToString("yymmssfff") + extension;

                    string path = Path.Combine(rutaCarpeta + "/Producto/", nombreArchivo);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await productos.Archivo.CopyToAsync(fileStream);
                    }
                    _context.Add(productos);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("ErrorProductos", "Debe seleccionar una imagen");
                    ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nombre");
                    return View(productos);
                }
            }
            ModelState.AddModelError("ErrorProductos", "Favor de revisar los datos");
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nombre");
            return View(productos);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productos = await _context.Producto.FindAsync(id);
            if (productos == null)
            {
                return NotFound();
            }
            return View(productos);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProducto,Nombre,Archivo,Precio,Stock,Descripcion,IdCategoria")] Productos productos)
        {
            if (id != productos.IdProducto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (productos.Archivo != null)
                    {
                        //Guardar la imagen en wwwroot/imagenes
                        string rutaCarpeta = webHostEnvironment.WebRootPath;
                        string nombreArchivo = Path.GetFileNameWithoutExtension(productos.Archivo.FileName);
                        string extension = Path.GetExtension(productos.Archivo.FileName);
                        //Asignar al atributo
                        productos.Imagen = nombreArchivo = nombreArchivo + DateTime.Now.ToString("yymmssfff") + extension;

                        string path = Path.Combine(rutaCarpeta + "/Producto/", nombreArchivo);
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await productos.Archivo.CopyToAsync(fileStream);
                        }
                        _context.Update(productos);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductosExists(productos.IdProducto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productos);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productos = await _context.Producto
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (productos == null)
            {
                return NotFound();
            }

            return View(productos);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productos = await _context.Producto.FindAsync(id);
            _context.Producto.Remove(productos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductosExists(int id)
        {
            return _context.Producto.Any(e => e.IdProducto == id);
        }
    }
}

YOLOTOL/SOURCE_CODE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YOLOTOL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/Home/Inicio.css" />
    <link rel="stylesheet" href="~/css/Home/Nosostros.css" />
    <link rel="stylesheet" href="~/css/Home/Contacto.css" />
    <link rel="stylesheet" href="~/css/boton.css" />
    <link rel="stylesheet" href="~/css/Card.css" />
    <link rel="manifest" href="~/manifest.json">
    <link rel="stylesheet" href="~/css/Catalogo/Details.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.css" rel="stylesheet" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <script type="module" src="~/pwabuilder-sw-register.js"></script>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css'>
    <link href='//netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' rel='stylesheet' />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>

    <nav class=" badge-light">
        <input type="checkbox" id="check">
        <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
        </label>
        <a href="#" class="enlace">
            <img href="#../Index" src="~/img/Home/Inicio_logo.png" alt="Logo" title="YOLOTOL" class="logo">
        </a>
        <ul>
            <li>
                <a class="button-27" asp-controller="Home" asp-action="Inicio">INICIO</a>
            </li>
            <li>
                <a class="button-24" asp-controller="Catalogo" asp-action="Index">TIENDA</a>
            </li>
            <li>
                <a class="button-25" asp-controller="Home" asp-action="Nosotros">NOSOTROS</a>
            </li>
            <li>
                <a class="button-26" asp-controller="Home" asp-action="Contacto">CONTÁCTANOS</a>
            </li>


            @if (User.Identity.IsAuthenticated)
            {
                <li>
                    <a class="button-28" role="button" asp-controller="Dashboard" asp-action="Index">PANEL</a>
                </li>
            }

            @if (User.Identity.IsAuthenticated)
            {
                <li><a class="button-29" asp-action="Logout" asp-controller="Login">CERRAR SESIÓN </a></li>
            }
            else
            {
                <li><a class="button-29" asp-action="Login" asp-controller="Home">INICIAR SESIÓN </a></li>
            }


        </ul>

    </nav>
    <hr class="hr" />





    <div class="btn-flotante btn-group dropup fixed-bottom box-shadow col-3">
        <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-shopping-cart"></i>
            <span class="badge badge-success">@ViewBag.count</span>

        </button>
        <div class="dropdown-menu">
            <div class="row total-header-section">
                <div class="col-lg-7 col-sm-7 col-7">
                    <i class="fa fa-shopping-bag" aria-hidden="true"
                       style="font-size: 20px; margin-right: 10px; color: #00bfeb;"></i>
                    <span class="badge badge-pill badge-danger" style="color: #00bfeb;">@ViewBag.count</span>
                </div>
                <div class="col-lg-7 col-sm-7 col-7 total-section text-right">
                    <p>Total: <span class="text-info">$@ViewBag.total</span></p>
                </div>
            </div>
            @if (ViewBag.cart != null)
            {
                @foreach (var item in ViewBag.cart)
                {
                    <div class="row cart-detail">
                        <div class="col-lg-4 col-sm-4 col-4 cart-detail-img">
                            <img src="~/Productos/@item.Producto.Imagen" width="50" />
                        </div>
                        <div class="col-lg-8 col-sm-8 col-8 cart-detail-product">
                            <p>@item.Producto.Nombre</p>
                            <span class="price text-info"> $@item.Producto.Precio</span> <span class="count"> Cantidad:@item.Quantity</span>
                        </div>
                    </div>
                }
            }
            else
            {
                <small style="color: red;">
                    Aún no hay productos en el carrito.
                </small>
            }
            <div class="row">
                <div class="col-lg-12 col-sm-12 text-center checkout">
                    <a type="button" class="btn text-white" asp-action="ShoppingCart" asp-controller="Catalogo" style="background: #00bfeb; ">
                        Ver todo
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="social-buttons btn-flotante">
        <a href="#" class="social-buttons__button social-button social-button--facebook" aria-label="Facebook">
            <i class="fab fa-facebook-f"></i>
        </a>
    </div>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer-distributed">

        <div class="footer-left">

            <h3>YOLOTOL</h3>

            <p class="footer-links">
                <a asp-controller="Home" asp-action="Inicio" class="text-white">Inicio</a>
                |
                <a class="text-white" asp-controller="Catalogo" asp-action="Index">Tienda</a>
                |
                <a asp-controller="Home" asp-action="Descargar" class="text-white">Descargar</a>
                |
                <a asp-controller="Home" asp-action="Nosotros" class="text-white">Nosotros</a>
            </p>

            <p class="footer-company-name">© 2022 EDEN -Todos los derechos reservados</p>
        </div>

        <div class="footer-center">
            <div>
                <i class="fa fa-phone"></i>
                <p>+52 2846598950</p>
            </div>
            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="">yolotol@gmail.com</a></p>
            </div>

        </div>
        <div class="footer-right">
            <p class="footer-company-about">
                <span> ¡Síguenos en nuestras redes sociales! </span>
                Regístrate para recibir noticias y actualizaciones sobres nuestros productos
            </p>
            <div class="footer-icons">
                <a href="#"><i class="fa fa-facebook"></i></a>

                <a href="#"><i class="fa fa-instagram"></i></a>

            </div>

        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Cart.js"></script>
    <script src="~/js/DatosJuga.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="path/to/chartjs/dist/chart.js"></script>
    <script>
        const myChart = new Chart(ctx, { ...});
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

YOLOTOL/SOURCE_CODE/Views/Shared/_LayoutDash.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" lang="es" />
    <title>@ViewData["Title"] - YOLOTOL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <script src="https://kit.fontawesome.com/1f837e8255.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Dashboard.css">

</head>

<body>
     <div class='dashboard'>
         <div class="dashboard-nav">

    <header>
     <div class="vertical-nav" id="sidebar" style="margin-bottom:90px; ">
         <div class="py-4 px-3 mb-4">
             <div class="media d-flex align-items-center">
                 <img src="~/img/Home/Nos-LogEden.png" width="65" class="mr-3 rounded-circle img-thumbnail">
                 <div class="media-body text-light">
                     <h4 class="m-0" style="">Abdiel Flores</h4>
                     <p class=" mb-0 text-light" style="font-family:'Oregon LDO'">Administrador</p>
                 </div>
             </div>
         </div>
     </div>
     </header>
     <br />
     <nav class="dashboard-nav-list">
         <a asp-action="Index" asp-controller="Dashboard" class="dashboard-nav-item">
             <i class="fas fa-home"></i>
             INICIO
         </a>
         <a href="#" class="dashboard-nav-item">
             <i class="fas fa-user"></i>
             PERFIL
         </a>
         <div class='dashboard-nav-dropdown'>
             <a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle">
                 <i class="fas fa-tools"></i>
                 ADMINISTRADOR
             </a>
             <div class='dashboard-nav-dropdown-menu'>
                 <a asp-action="Index" asp-controller="Usuarios" class="dashboard-nav-dropdown-item">Usuarios</a>
                 <a asp-action="Index" asp-controller="Productos" class="dashboard-nav-dropdown-item">Productos</a>
                 <a asp-action="Index" asp-controller="Categorias" class="dashboard-nav-dropdown-item">Categorias</a>
                 <a asp-action="Index" asp-controller="TiposDeUsuarios" class="dashboard-nav-dropdown-item">Tipo de usuario</a>
                 <a asp-action="Index" asp-controller="Direcciones" class="dashboard-nav-dropdown-item">Direcciones</a>
             </div>
         </div>
         <div class='dashboard-nav-dropdown'>
             <a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle">
                 <i class="fas fa-users"></i>
                 PADRES
             </a>
             <div class='dashboard-nav-dropdown-menu'>
                 <a asp-action="Datos" asp-controller="Dashboard" class="dashboard-nav-dropdown-item">Perfil del jugador</a>
                 <a asp-action="Index" asp-controller="Direcciones" class="dashboard-nav-dropdown-item">Direcciones</a>
             </div>
         </div>
         <div class='dashboard-nav-dropdown'>
             <a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle">
                 <i class="fas fa-brain"></i> PROFESIONALES
             </a>
             <div class='dashboard-nav-dropdown-menu'>
                 <a asp-action="Index" asp-controller="Usuarios" class="dashboard-nav-dropdown-item">Jugadores</a>
                 <a asp-action="Datos" asp-controller="Dashboard" class="dashboard-nav-dropdown-item">Perfil del jugador</a>
             </div>
         </div>
         <a href="#" class="dashboard-nav-item">
             <i class="fas fa-cogs"></i>
             AJUSTES
         </a>

         <div class="nav-item-divider"></div>
         <a asp-action="Logout" asp-controller="Login" class="dashboard-nav-item">
             <i class="fas fa-sign-out-alt"></i>
             Cerrar sesión
         </a>
     </nav>
     </div>
     <div class='dashboard-app'>
         <header class='dashboard-toolbar'>
             <a href="#!" class="menu-toggle"><i class="fas fa-bars"></i></a>
             <div class="position-absolute top-50 start-50 translate-middle">
                 <img width="200" class="" src="~/img/Dashboard/LogoYolotol22.png">
             </div>
             

             <div class="dropdown" style="padding: 5px; justify-content: right; margin-left:75%;">
                 <button type="button" class="btn" data-toggle="dropdown" asp-action="Inicio" asp-controller="Home">
                     <img src="~/img/Home/Nos-LogEden.png" width="50" class="mr-3 rounded-circle img-thumbnail">
                 </button>

                 <div class="dropdown-menu dropdown-menu-end">
                     <div aria-hidden="true" aria-labelledby="dropdownMenuLink">
                         <a class="dropdown-item " asp-action="Inicio" asp-controller="Home"><i class="fas fa-chevron-circle-left"></i> Volver al sitio</a>
                         <a class="dropdown-item"  asp-controller="Catalogo" asp-action="Index"><i class="fas fa-shopping-basket"></i> Tienda</a>
                         <a class="dropdown-item" asp-action="Logout" asp-controller="Login"><i class="fa fa-sign-out"></i> Cerrar sesión</a>
                     </div>
                 </div>
             </div>

         </header>




    <div class='dashboard-content'>
        <div class='container'>
            <main role="main" class="pb-1" style="">
                @RenderBody()
            </main>
        </div>
    </div>
    </div>


    </div>

  





    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/all.js"></script>
    <script src="~/js/Dasboard.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>