YOLOTOL/SOURCE_CODE/Controllers/CatalogoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YOLOTOL.Data;
using YOLOTOL.Helpers;
using YOLOTOL.Models;

namespace YOLOTOL.Controllers
{
    public class CatalogoController : Controller
    {
        private readonly YolotolContext _context;
        public CatalogoController(YolotolContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");//Obtener la lista
            if (cart != null)
            {
                ViewBag.count = cart.Count;//Contando el número de elementos en el carrito
                ViewBag.cart = cart;//Elementos del carrito
                ViewBag.total = cart.Sum(item => item.Producto.Precio * item.Quantity);//calCULO total = x cada elemento del cart presio*cantidad
                ViewBag.cantidad = cart.Sum(item => item.Quantity);//Calculo cantidad
            }
            return View(await _context.Producto.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var producto = await _context.Producto.FirstOrDefaultAsync(m => m.IdProducto == id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        public async Task<IActionResult> ShoppingCart()
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");//Obtener la lista
            if (cart != null)
            {
                ViewBag.count = cart.Count;//Contando el número de elementos en el carrito
                ViewBag.cart = cart;//Elementos del carrito
                ViewBag.total = cart.Sum(item => item.Producto.Precio * item.Quantity);//calCULO total = x cada elemento del cart presio*cantidad
                ViewBag.cantidad = cart.Sum(item => item.Quantity);//Calculo cantidad
            }
            return View(await _context.Producto.ToListAsync());
        }

        public async Task<IActionResult> AddToCart(int? id)
        {
            Productos productos = new Productos();
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                List<CartItem> cart = new List<CartItem>();//Crear variable(carrito)
                var producto = await _context.Producto.FirstOrDefaultAsync(m => m.IdProducto == id);//Busca el producto y lo guarda
                cart.Add(new CartItem { Producto = producto, Quantity = 1 });//Agrega el elemento al carrito, es decir el producto o la cantidad
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);//El elemento del carrito lo guarda en la sesión
            }
            else
            {
                List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    var producto = await _context.Producto.FirstOrDefaultAsync(m => m.IdProducto == id);//Busca el producto y lo guarda
                    cart.Add(new CartItem { Producto = producto, Quantity = 1 });//Agrega el elemento al carrito, es decir el producto o la cantidad
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);//El elemento del carrito lo guarda en la sesión

            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Update(int? id, int quantity)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");//Obtener la lista
            int index = isExist(id);
            if (index != -1)
            {
                cart[index].Quantity = quantity;
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("ShoppingCart");

        }

        public async Task<IActionResult> Remove(int? id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");//Obtener la lista
            int index = isExist(id);
            if (index != -1 && cart.Count > 1)
            {
                cart.RemoveAt(index);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else if (index != -1 && cart.Count == 1)
            {
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", null);
            }
            return RedirectToAction("ShoppingCart");

        }

        private int isExist(int? id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Producto.IdProducto.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

YOLOTOL/SOURCE_CODE/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YOLOTOL.Helpers;
using YOLOTOL.Models;
using YOLOTOL.Services;

namespace YOLOTOL.Controllers
{
    public class PaymentController : Controller
    {
        #region Single Paypal Payment
        public IActionResult CreatePayment()
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");//Obtener la lista
            var payment = PayPalPaymentService.CreatePayment(GetBaseUrl(), "sale", cart);
            return Redirect(payment.GetApprovalUrl());
        }

        public IActionResult PaymentSuccessful(string paymentId, string token, string PayerId)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            var payment = PayPalPaymentService.ExecutePayment(paymentId, PayerId);
            if (cart != null)
            {
                ViewBag.cart = cart;
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", null);
            //Info del cliente
            Payer payer = payment.payer;
            ViewBag.cliente = payer.payer_info;
            //Dirección del cliente
            ViewBag.direccion = payer.payer_info.shipping_address;
            //Detalles de la transaccion
            List<Transaction> transactions = payment.transactions;
            foreach (var detail in transactions)
            {
                ViewBag.importe = detail.amount;
                ViewBag.detalles = detail.amount.details;
                ViewBag.articulos = detail.item_list.items;
            }
            return View();
        }
        #endregion 

        public string GetBaseUrl()
        {
            return Request.Scheme + "://" + Request.Host;
        }
    }

}

YOLOTOL/SOURCE_CODE/Views/Catalogo/Details.cshtml
@model YOLOTOL.Models.Productos
@{

    ViewData["Title"] = "Detalles";
}

<section class="py-5" style="font-family:'Oregon LDO'">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="~/Producto/@Html.DisplayFor(model => model.Imagen)" alt="..." /></div>
            <div class="col-md-6">
                <h1 class="display-5 fw-bolder">@Html.DisplayFor(model => model.Nombre)</h1>
                <div class="fs-5 mb-5">

                    <span>$@Html.DisplayFor(model => model.Precio)</span>
                </div>
                <p class="lead">@Html.DisplayFor(model => model.Descripcion)</p>
                <div >
                    <a  style="  margin-left:10%;"asp-action="Index" asp-controller="Catalogo" class="btn-d text-white">Regresar</a>
                </div>
            </div>
        </div>
    </div>
</section>

YOLOTOL/SOURCE_CODE/Views/Catalogo/Index.cshtml
@model IEnumerable<YOLOTOL.Models.Productos>

@{
    ViewData["Title"] = "Catálogo";
}

<header class="bg-info-50 py-5 " style="font-family: Oregon LDO">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-4 fw-bolder text-dark mb-2 font-weight-bold">Productos YOLOTOL</h1>
                    <p class=" lead fw-normal text-dark-50 mb-2">Encuentra una gran variedad de productos al mejor precio.</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-center align-content-center text-center">
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src="~/img/Home/Des_banner.png" alt="YOLOTOL" title="YOLOTOL" /></div>
        </div>
    </div>
</header>
<hr />
<div class="container" style="font-family:'Oregon LDO'">
    <div class="row justify-content-center">
        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <div class="contenedor container m-md-4 box-shadow" style="background-color: #f2f2f2">
                    <img class="card-img-top" src="~/Producto/@Html.DisplayFor(modelItem => item.Imagen)" style="height: 225px; width: 100%; display: block;" />
                    <div class="card-body">
                        <h4>@Html.DisplayFor(modelItem => item.Nombre)</h4>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.Descripcion)</p>
                        <p><strong>Precio $@Html.DisplayFor(modelItem => item.Precio)MNX</strong></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a asp-action="Details" asp-route-id="@item.IdProducto" type="submit" class="btn btn-sm btn-outline-info">Ver más</a>

                                <a asp-action="AddToCart" asp-route-id="@item.IdProducto" type="submit" class="btn btn-sm btn-outline-info">Agregar al carrito</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

YOLOTOL/SOURCE_CODE/Views/Catalogo/ShoppingCart.cshtml
@{
    ViewData["Title"] = "Carrito";
}

<br />
<h1 class="text-info">Carrito de compras</h1>

<div class="container">
    <div class="row">
        @if (ViewBag.cart != null)
        {
            <div class="col-md-9 ">
                <table id="Cart" class="table">
                    <thead>
                        <tr class="">
                            <th style="width:50%">Producto</th>
                            <th style="width:10%">Precio</th>
                            <th style="width:8%">Cantidad</th>
                            <th style="width:22%">Subtotal</th>
                            <th style="width:10%">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.cart)
                        {
                            <tr>
                                <td data-th="Producto">
                                    <div class="row">
                                        <div class="col-sm-4 hidden-xs">
                                            <img src="~/Producto/@item.Producto.Imagen" width="100" class="img-responsive">
                                        </div>
                                        <div class="col-sm-8">
                                            <h4 class="nomargin text-white">@item.Producto.Nombre</h4>
                                        </div>
                                    </div>
                                </td>
                                <td data-th="Precio" class="">$@item.Producto.Precio MXN</td>
                                <td data-th="Cantidad" class="">
                                    <input type="number" id="quantity" name="quantity" class="form-control text-center cantidad" value="@item.Quantity" />
                                </td>
                                <td data-th="Subtotal" class="">$@(item.Quantity * item.Producto.Precio) MXN</td>
                                <td data-th="Opciones">
                                    <button asp-action="Update" class="btn btn-info btn-sm update-cart" data-id="@item.Producto.IdProducto"><i class="fas fa-sync-alt"></i></button>
                                    <a asp-action="Remove" asp-route-id="@item.Producto.IdProducto" class="btn btn-danger btn-sm"><i class="fas fa-trash" aria-hidden="true"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr class="visible-xs">
                            <td class="text-center"><strong style="color:#336633">Total: $@ViewBag.total MXN</strong></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <div class="col-md-3 justify-content-center">
                <div class="contenedor mb-4 box-shadow" style="position: sticky!important; top:0">
                    <div class="card-body">
                        @if (ViewBag.count > 1)
                        {
                            <h5>Cantidad: @ViewBag.count productos</h5>
                            <h5>Total: $@ViewBag.total MXN</h5>
                            <div class="text-center">
                                <a class="btn" style="width:200px; background: #336633;" asp-controller="Payment" asp-action="CreatePayment"><i class="fab fa-paypal"></i>Pagar con Paypal</a>
                                <a class="btn" style="width:200px; background: #b23434;"><i class="fas fa-angle-left"></i>Continuar comprando</a>
                            </div>
                        }
                        else if (ViewBag.count == 1)
                        {
                            <h5>Cantidad: @ViewBag.count producto</h5>
                            <h5>Total: $@ViewBag.total MXN</h5>
                            <div class="text-center">
                                <a class="btn " style="width:200px; background: #336633;" asp-controller="Payment" asp-action="CreatePayment"><i class="fab fa-paypal"></i>Pagar con Paypal</a>
                                <a class="btn " style="width:200px; background: #b23434;"><i class="fas fa-angle-left"></i>Continuar comprando</a>
                            </div>
                        }
                        else if (ViewBag.cantidad == 0)
                        {
                            <h5>La cantidad de sus productos está en 0. ¡Compre algo!</h5>
                        }
                        <br />
                    </div>
                </div>
            </div>
        }
        else
        {
            <h3 style="color: black">No ha agregado productos a su carrito, ¿Qué espera?</h3>
        }
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        function getAbsolutePath() {
            var loc = window.location;
            var pathName = loc.pathname.substring(0, loc.pathname.lastIndexOf('/') + 1);
            return loc.href.substring(0, loc.href.length - ((loc.pathname + loc.search + loc.hash).length - pathName.length));
        }
        var urlUpdate = getAbsolutePath() + 'Update';
        $(".update-cart").click(function (e) {
            e.preventDefault();
            var c = $(this);
            $.ajax({
                type: 'POST',
                url: urlUpdate,
                data: {
                    id: c.attr("data-id"),
                    quantity: c.parents("tr").find(".cantidad").val()
                },
                success: function (response) {
                    window.location.reload();
                    console.log("Success.");
                },
                error: function (response) {
                    console.log("Error al actualizar cantidad.");
                }
            });
        });
    });
</script>